### Dell Global Operations Data Science/Analytics Case Study

In [262]:
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#### View Tables

In [263]:
ROOT = Path("/Users/2005b/Downloads/Job, College Application Files/OAs & Case Studies/Dell Data Science Case Study - March 2026")

calendar = pd.read_parquet(ROOT / "Data/calendar.parquet")
capacity = pd.read_parquet(ROOT / "Data/capacity.parquet")
expected_minutes = pd.read_parquet(ROOT / "Data/expected_minutes.parquet")
inference = pd.read_parquet(ROOT / "Data/inference.parquet")
train = pd.read_parquet(ROOT / "Data/train.parquet")

In [264]:
calendar.head()
# print(calendar.isna().sum())

,date,site,fiscal_year,fiscal_qtr,fiscal_month,fiscal_qtr_weeknum,fiscal_weeknum,fisc_week_val,calendar_day,day_of_week,calendar_weeknum,calendar_month,calendar_year,is_weekend,is_holiday,is_idc,is_eoq
0,2025-05-02,FCJ,2026,1,3,13,13,2026-W13,2,7,18,5,2025,0,0,0,1
1,2025-08-28,FCJ,2026,3,7,4,30,2026-W30,28,6,35,8,2025,0,0,0,0
2,2025-10-05,FCJ,2026,3,9,10,36,2026-W36,5,2,40,10,2025,1,0,0,0
3,2025-12-29,FCJ,2026,4,12,9,48,2026-W48,29,3,52,12,2025,0,0,0,0
4,2025-04-28,FCJ,2026,1,3,13,13,2026-W13,28,3,17,4,2025,0,0,0,1

In [265]:
capacity.head()
# print(capacity.isna().sum())

        date  ot_flag  ot_hours  regular_hours
0 2025-03-07        1       5.5           16.0
1 2025-03-07        1       5.5           16.0
2 2025-03-07        1       5.5           16.0
3 2025-03-07        1       5.5           16.0
4 2025-03-08        1       7.5           10.5

In [266]:
# Product features table
# print(expected_minutes.isna().sum())
# expected_minutes[expected_minutes.family_desc.isna()]
expected_minutes = expected_minutes.dropna()

expected_minutes.head()

,family_desc,expected_build_minutes,expected_burn_minutes,expected_kit_minutes
0,HFSDTS UJ,94.9401,2071.8561,2155.7586
1,MZWFHFS AXFSWS,84.3857,1080.5524,1464.1714
2,MZWFHFS IXX,84.3857,1080.5524,1464.1714
3,SFANIFI UJ,296.6429,4330.5714,1895.2857
4,HTKKJJ RNQQ TJRWIXX,69.4976,1436.1106,2033.6107

In [267]:
# Test data
inference.head()

,sales_order_id,buid,site,orig_wo_id,tie_num,mcid,order_amt,quantity_produced,line_qty,cfs_flag,is_cfi,alt_type_desc,lob_desc,family_parent_desc,family_desc,download_date,kit_start,est_ship_date
0,1026073335,11,KHO,22117639095,1,KHO,52526.77737,6,6,0,1,NSYJLWFYJI XTQZYNTSX LWTZU UGZ,UTBJWJILJ,HMFRUNTS,HMFRUNTS IXX,2026-02-12,2026-02-13,2026-02-19
1,1027826085,11,KHO,22114646815,1,3JU,253966.42809,1,1,0,1,NSYJLWFYJI XTQZYNTSX LWTZU UGZ,UTBJWJILJ,UFQT AJWIJ,UFQT AJWIJ UJ,2026-02-04,2026-02-10,2026-04-03
2,1029739753,11,KHO,22116037515,1,KHO,46049.54133,8,8,0,1,NSYJLWFYJI XTQZYNTSX LWTZU UGZ,UTBJWJILJ,HTSHMT,HTSHMT UJ,2026-02-09,2026-02-26,2026-04-20
3,1030454098,11,KHO,22117289705,1,KHO,187435.69692,10,3,0,1,NSYJLWFYJI XTQZYNTSX LWTZU UGZ,XYTWFLJ ZSXYWZHYZWJI,HQJJP K710,HQJJP-K710,2026-02-12,2026-02-12,2026-05-20
4,1029526599,11,KHO,22110817985,1,3JU,24400.99320,8,8,0,1,NSYJLWFYJI XTQZYNTSX LWTZU UGZ,UTBJWJILJ,UFYWFX,UFYWFX TJRW,2026-01-27,2026-02-11,2026-04-27

In [268]:
# Product order table
train.head()

,sales_order_id,buid,site,orig_wo_id,tie_num,mcid,order_amt,quantity_produced,line_qty,cfs_flag,is_cfi,alt_type_desc,lob_desc,family_parent_desc,family_desc,download_date,kit_start,kit_end,est_ship_date
0,1025548771,11,KHO,22067915245,1,3JU,42935.31840,8,8,0,1,NSYJLWFYJI XTQZYNTSX LWTZU UGZ,UTBJWJILJ,LJSYWD,LJSYWD HXU,2025-10-15,2025-10-16,2025-10-17,2025-10-31
1,1027927868,11,KHO,22095717945,1,KHO,33128.74827,2,2,0,1,NSYJLWFYJI XTQZYNTSX LWTZU UGZ,UTBJWJILJ,HMFRUNTS,HMFRUNTS AXFSWS,2025-12-11,2025-12-12,2025-12-14,2026-03-16
2,1029939204,11,KHO,22112237255,1,KHO,17238.22614,1,1,0,1,NSYJLWFYJI XTQZYNTSX LWTZU UGZ,UTBJWJILJ,HMFRUNTS,HMFRUNTS UJ,2026-01-29,2026-01-30,2026-02-03,2026-06-17
3,1023379512,11,KHO,22082951775,1,3JU,34306.97076,6,6,0,1,NSYJLWFYJI XTQZYNTSX LWTZU UGZ,UTBJWJILJ,RNZWF,RNZWF UJ,2025-11-19,2025-11-29,2025-11-30,2025-11-12
4,1017735495,707,KHO,21983065475,1,KHO,6261.03846,1,1,0,0,NSYJLWFYJI XTQZYNTSX LWTZU UGZ,UTBJWJILJ,MZWFHFS,MZWFHFS UJ,2025-04-01,2025-04-03,2025-04-04,2025-04-16

#### EDA

In [269]:
print("Look at Rows and Columns:")
print("----------------------------------------------")
print(train.info())

print("\n# of Duplicate Rows per Column:")
print("----------------------------------------------")
print(train[train.duplicated(keep=False)])

print("\n# of Unique Values per Column:")
print("----------------------------------------------")
unique_counts = train.nunique().sort_values()
print(unique_counts)

Look at Rows and Columns:
----------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 179853 entries, 0 to 179852
Data columns (total 19 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   sales_order_id      179853 non-null  int64
 1   buid                179853 non-null  object
 2   site                179853 non-null  str
 3   orig_wo_id          179853 non-null  int64
 4   tie_num             179853 non-null  object
 5   mcid                179853 non-null  str
 6   order_amt           179853 non-null  float64
 7   quantity_produced   179853 non-null  object
 8   line_qty            179853 non-null  object
 9   cfs_flag            179853 non-null  int64
 10  is_cfi              179853 non-null  int64
 11  alt_type_desc       179853 non-null  str
 12  lob_desc            179853 non-null  str
 13  family_parent_desc  179853 non-null  str
 14  family_desc         179853 non-null  str
 15  download_date       179848 non-null  datetime64[ns]
 16  kit_start           179853 non-null  datetime64[ns]
 17  kit_end             179853 non-null  datetime64[ns]
 18  est_ship_date       179853 non-null  datetime64[ns]
dtypes: datetime64[ns](4), float64(1), int64(4), object(4), str(6)
memory usage: 37.6+ MB
None

# of Duplicate Rows per Column:
----------------------------------------------
Empty DataFrame
Columns: [sales_order_id, buid, site, orig_wo_id, tie_num, mcid, order_amt, quantity_produced, line_qty, cfs_flag, is_cfi, alt_type_desc, lob_desc, family_parent_desc, family_desc, download_date, kit_start, kit_end, est_ship_date]
Index: []

# of Unique Values per Column:
----------------------------------------------
site                       1
alt_type_desc              1
cfs_flag                   2
is_cfi                     2
buid                       3
mcid                       8
tie_num                    8
lob_desc                  10
line_qty                  14
quantity_produced         33
family_parent_desc       216
kit_start                289
kit_end                  338
download_date            352
family_desc              360
est_ship_date            486
order_amt              52718
sales_order_id        172234
orig_wo_id            172234
dtype: int64

In [270]:
nulls = pd.DataFrame({
    "na_count": train.isna().sum(),
    "na_percent": train.isna().mean() * 100
})

nulls = nulls.sort_values("na_percent", ascending=False)

display(nulls)

                    na_count  na_percent
download_date              5     0.00278
buid                       0     0.00000
sales_order_id             0     0.00000
site                       0     0.00000
orig_wo_id                 0     0.00000
mcid                       0     0.00000
tie_num                    0     0.00000
quantity_produced          0     0.00000
line_qty                   0     0.00000
cfs_flag                   0     0.00000
order_amt                  0     0.00000
is_cfi                     0     0.00000
alt_type_desc              0     0.00000
family_parent_desc         0     0.00000
lob_desc                   0     0.00000
family_desc                0     0.00000
kit_start                  0     0.00000
kit_end                    0     0.00000
est_ship_date              0     0.00000

In [271]:
# Look at rows with null values, all from same build and site, but number of rows is negligible so it is fine to drop
# train[train.download_date.isna()]
train = train.dropna()

#### Pre-Modeling

In [272]:
# Create target feature for easier training
train["kit_start"] = pd.to_datetime(train["kit_start"])
train["kit_end"] = pd.to_datetime(train["kit_end"])

train["build_duration_days"] = (
    train["kit_end"] - train["kit_start"]
).dt.total_seconds() / 86400

In [273]:
print(train["build_duration_days"].describe())

print("Missing targets:", train["build_duration_days"].isna().sum() / len(train["kit_start"]), "%")
print("Negative timelines:", (train["build_duration_days"] < 0).sum() / len(train["kit_start"]), "%")

count    179848.000000
mean          1.338530
std           1.629429
min         -25.000000
25%           1.000000
50%           1.000000
75%           2.000000
max          76.000000
Name: build_duration_days, dtype: float64
Missing targets: 0.0 %
Negative timelines: 0.004081224144833415 %

In [274]:
# Remove rows with negative timelines as they make up a small percentage of the data
train = train[train["build_duration_days"] >= 0]

In [275]:
# Normalize date features
train["download_date"] = pd.to_datetime(train["download_date"]).dt.normalize()
train["kit_start"] = pd.to_datetime(train["kit_start"]).dt.normalize()
train["kit_end"] = pd.to_datetime(train["kit_end"]).dt.normalize()
train["est_ship_date"] = pd.to_datetime(train["est_ship_date"]).dt.normalize()
calendar["date"] = pd.to_datetime(calendar["date"]).dt.normalize()
capacity["date"] = pd.to_datetime(capacity["date"]).dt.normalize()

# Join tables
df = train.merge(expected_minutes, on="family_desc", how="left", validate="m:1")
df = df.merge(calendar, left_on="kit_start", right_on = "date", how="left", validate="m:1").drop(columns=["date", "site_y"])
df = df.merge(capacity, left_on="kit_start", right_on = "date", how="left", validate="m:1").drop(columns=["date"])

MergeError: Merge keys are not unique in right dataset; not a many-to-one merge

Duplicates in right:
       date
2025-03-07
2025-03-07
2025-03-07
2025-03-08
2025-03-08 ...

In [276]:
# Duplicate keys prevented merging with df
duplicates = capacity[capacity.duplicated("date", keep=False)].sort_values("date")
print(len(capacity), capacity["date"].nunique())
print(duplicates.head())

191934 317
             date  ot_flag  ot_hours  regular_hours
138238 2025-03-04        0       0.0            0.0
101880 2025-03-04        0       0.0            0.0
73951  2025-03-04        0       0.0            0.0
46212  2025-03-04        0       0.0            0.0
237    2025-03-04        0       0.0            0.0

In [277]:
capacity = capacity.drop_duplicates()

# Try join again
df = df.merge(capacity, left_on="kit_start", right_on = "date", how="left", validate="m:1").drop(columns=["date"])

In [278]:
# Sanity check for df joining
print(df.isna().sum())
print(len(df))

sales_order_id                0
buid                          0
site_x                        0
orig_wo_id                    0
tie_num                       0
mcid                          0
order_amt                     0
quantity_produced             0
line_qty                      0
cfs_flag                      0
is_cfi                        0
alt_type_desc                 0
lob_desc                      0
family_parent_desc            0
family_desc                   0
download_date                 0
kit_start                     0
kit_end                       0
est_ship_date                 0
build_duration_days           0
expected_build_minutes    52353
expected_burn_minutes     52353
expected_kit_minutes      52353
fiscal_year                   5
fiscal_qtr                    5
fiscal_month                  5
fiscal_qtr_weeknum            5
fiscal_weeknum                5
fisc_week_val                 5
calendar_day                  5
day_of_week                   5
calendar_weeknum              5
calendar_month                5
calendar_year                 5
is_weekend                    5
is_holiday                    5
is_idc                        5
is_eoq                        5
ot_flag                       0
ot_hours                      0
regular_hours                 0
dtype: int64
179114

In [279]:
null_dates = df[df.fiscal_year.isna()]
print(null_dates[["sales_order_id", "download_date", "kit_start", "kit_end"]])
print(calendar.date.min(), calendar.date.max())
# kit_start dates start before min calendar date, number of rows is negligible so it is fine to drop

df = df.dropna(subset=["fiscal_year"])

        sales_order_id download_date  kit_start    kit_end
15304       1016474537    2025-03-03 2025-03-04 2025-03-14
62406       1016470895    2025-03-01 2025-03-04 2025-03-12
106259      1016019103    2025-02-25 2025-03-04 2025-03-14
134676      1016483537    2025-03-01 2025-03-04 2025-03-14
141652      1016524375    2025-03-03 2025-03-04 2025-03-14
2025-03-06 00:00:00 2026-03-10 00:00:00

In [ ]:
missing = df[df.expected_kit_minutes.isna()]
print(missing.family_desc.nunique(), "families missing of", df.family_desc.nunique())
print("\n", missing.family_desc.value_counts().head())
print("\n", missing.groupby("lob_desc").size().sort_values(ascending=False).head())
print("\n", missing.kit_start.dt.to_period("M").value_counts().sort_index())
# Take note of missing product order features, they account for 29% of the data, action can be taken later (imputation?)

215 families missing of 360

 family_desc
LQFIJBFYJW UJ         6668
LNGGTSXHWJJP UJ       4397
RNZWF UJ              3033
LNGGTSXHWJJP TJRCQ    1589
HMFRUNTS TJRCQ        1577
Name: count, dtype: int64

 lob_desc
UTBJWJILJ                      40273
MDUJWHTSAJWLJI NSKWFX YWFSX     5398
IJQQ XYTWFLJ TJR                3325
IFYF UWTYJHYNTS FUU YWFSX       1978
XYTWFLJ ZSXYWZHYZWJI            1093
dtype: int64

 kit_start
2025-03    5919
2025-04    5320
2025-05    4538
2025-06    3471
2025-07    6405
2025-08    4960
2025-09    4324
2025-10    5402
2025-11    3793
2025-12    4262
2026-01    3959
Freq: M, Name: count, dtype: int64

In [281]:
# Create numeric variables for XGBoost to train on
df["queue_days"] = (df["kit_start"] - df["download_date"]).dt.days
df["ship_slack_days"] = (df["est_ship_date"] - df["kit_start"]).dt.days

#### Modeling

In [282]:
# Join features to inference
X_inf = inference.merge(expected_minutes, on="family_desc", how="left", validate="m:1")
X_inf = X_inf.merge(calendar, left_on="kit_start", right_on = "date", how="left", validate="m:1").drop(columns=["date", "site_y"])
X_inf = X_inf.merge(capacity, left_on="kit_start", right_on = "date", how="left", validate="m:1").drop(columns=["date"])
X_inf["queue_days"] = (X_inf["kit_start"] - X_inf["download_date"]).dt.days
X_inf["ship_slack_days"] = (X_inf["est_ship_date"] - X_inf["kit_start"]).dt.days

# X_inf.isna().sum()

In [283]:
import xgboost as xgb # robust boosting model to use for initial baseline for case study

num_cols = ["buid", "tie_num", "quantity_produced", "line_qty", "expected_build_minutes", "expected_burn_minutes", "expected_kit_minutes"]
cat_cols = ["site_x", "mcid", "alt_type_desc", "lob_desc", "family_parent_desc", "family_desc", "fisc_week_val"]
drop_cols = ["download_date", "kit_start", "kit_end", "est_ship_date", "build_duration_days"]
features = [c for c in df.columns if c not in drop_cols]

# XGBoost needs numeric or category type
for c in num_cols:
    df[c] = pd.to_numeric(df[c], errors="coerce")
    X_inf[c] = pd.to_numeric(X_inf[c], errors="coerce")
for col in cat_cols:
    df[col] = df[col].astype('category')
    X_inf[col] = X_inf[col].astype(pd.CategoricalDtype(categories=df[col].cat.categories)) # maps unknown categories to NaN before prediction

X = df[features].copy()
y = df["build_duration_days"]
X_inf = X_inf[features].copy()   

model = xgb.XGBRegressor(
    n_estimators=500, learning_rate=0.05, max_depth=6,
    subsample=0.8, colsample_bytree=0.8,
    tree_method="hist", enable_categorical=True,
    objective="reg:absoluteerror", random_state=42,
) # can tune hyperparameters and validate further down the road, past case study timeline
model.fit(X, y)

preds = np.rint(model.predict(X_inf))
pred_kit_end = inference["kit_start"] + pd.to_timedelta(preds, unit="D")

C:\Users\2005b\AppData\Local\Temp\ipykernel_11984\682049740.py:14: Pandas4Warning: Constructing a Categorical with a dtype and values containing non-null entries not in that dtype's categories is deprecated and will raise in a future version.
  X_inf[col] = X_inf[col].astype(pd.CategoricalDtype(categories=df[col].cat.categories)) # maps unknown categories to NaN before prediction
C:\Users\2005b\AppData\Local\Temp\ipykernel_11984\682049740.py:14: Pandas4Warning: Constructing a Categorical with a dtype and values containing non-null entries not in that dtype's categories is deprecated and will raise in a future version.
  X_inf[col] = X_inf[col].astype(pd.CategoricalDtype(categories=df[col].cat.categories)) # maps unknown categories to NaN before prediction
C:\Users\2005b\AppData\Local\Temp\ipykernel_11984\682049740.py:14: Pandas4Warning: Constructing a Categorical with a dtype and values containing non-null entries not in that dtype's categories is deprecated and will raise in a future version.
  X_inf[col] = X_inf[col].astype(pd.CategoricalDtype(categories=df[col].cat.categories)) # maps unknown categories to NaN before prediction

In [284]:
results = pd.DataFrame({
    "Kit Start Date": inference["kit_start"],
    "Predicted Kit End Date": pred_kit_end
})

display(results)
# Can compare predicted vs. actual kit_end by site, order quantity, fiscal quarter, etc.

      Kit Start Date Predicted Kit End Date
0         2026-02-13             2026-02-18
1         2026-02-10             2026-02-14
2         2026-02-26             2026-03-03
3         2026-02-12             2026-02-16
4         2026-02-11             2026-02-15
...              ...                    ...
12064     2026-02-25             2026-03-02
12065     2026-02-18             2026-02-22
12066     2026-02-10             2026-02-15
12067     2026-02-18             2026-02-22
12068     2026-02-03             2026-02-05

[12069 rows x 2 columns]

In [285]:
feature_ranking = pd.DataFrame({
    'Feature': features,
    'Importance Score': model.feature_importances_
})

feature_ranking = feature_ranking.sort_values(by='Importance Score', ascending=False).reset_index(drop=True)

display(feature_ranking) # can look at SHAP values down the road as well

                   Feature  Importance Score
0            regular_hours          0.556305
1           fiscal_weeknum          0.052386
2              day_of_week          0.047419
3           calendar_month          0.044217
4                 ot_hours          0.040842
5             fiscal_month          0.028470
6                  ot_flag          0.024089
7       fiscal_qtr_weeknum          0.018489
8            fisc_week_val          0.017824
9               is_holiday          0.017440
10             family_desc          0.016720
11        calendar_weeknum          0.013691
12              orig_wo_id          0.013155
13      family_parent_desc          0.012968
14  expected_build_minutes          0.010722
15             fiscal_year          0.008677
16            calendar_day          0.008338
17              queue_days          0.008253
18              fiscal_qtr          0.006393
19   expected_burn_minutes          0.005725
20              is_weekend          0.004738
21                  is_idc          0.004493
22    expected_kit_minutes          0.004456
23          sales_order_id          0.004267
24       quantity_produced          0.004010
25                line_qty          0.003819
26                cfs_flag          0.003608
27         ship_slack_days          0.003202
28                lob_desc          0.003146
29                  is_eoq          0.002847
30                    mcid          0.002402
31                  is_cfi          0.002334
32               order_amt          0.001665
33                 tie_num          0.001576
34                    buid          0.001311
35                  site_x          0.000000
36           alt_type_desc          0.000000
37           calendar_year          0.000000